CREATE TABLE IF NOT EXISTS PRODUCTS (
    PRODUCT_ID TEXT,
    NAME_ID TEXT,
    SUPPLIER_ID TEXT,
    CATEGORY_ID TEXT,
    UNTIL_ID TEXT,
    PRICE_REAL 

);


INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, SUPPLIER_ID, CATEGORY_ID, UNIT_TEXT, PRICE_REAL) VALUES
('1', 'CHAIS', '1', '1', '10 BOXES*20 BAGS', 18),
('2', 'CHANG', '1', '1', '24-12 OZ BOTTLES', 19),
('3', 'ANISEED SYRUP', '1', '2', '12-550 ML BOTTLES', 10),
('4', 'CHEF ANTON SEASONING', '2', '2', '48-6 OZ JARS', 22),
('5', 'CHEF ANTON MIX', '2', '2', '36 BOXES', 21.35);

);

SELECT * FROM PRODUCTS;

SELECT COUNT(PRODUCT_ID) As Product_Count
FROM PRODUCTS;

SELECT AVG(PRICE_REAL) AS Average_Price
FROM PRODUCTS;

SELECT SUM(PRICE) AS Total_Price
FROM PRODUCTS;









